server:
  port: 8099

spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
  timeZone: GMT+8
  devtools:
    restart:
      enabled: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 3000


# logging
logging:
  level:
    root: info